version: '2'

networks:
  faulty-net:

services:
  # app:
  #   image: some-image
  #   links:
  #     - redis-sentinel

  redis-master:
    image: redis:3.2.5-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
    networks:
      - faulty-net

  redis-slave:
    image: redis:3.2.5-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
    networks:
      - faulty-net

  # Instance 1
  redis-sentinel:
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - faulty-net

  # Instance 2
  redis-sentinel2:
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - faulty-net

  # Instance 3
  redis-sentinel3:
    build:
      context: ./redis-sentinel
    links:
      - redis-master
    networks:
      - faulty-net

  gremlins:
    image: qualimente/gremlins
    volumes:
      - ./gremlins/profiles:/app/gremlins/profiles
    command: gremlins -m gremlins.profiles.redis_faults -p redis_faults.profile
    network_mode: "service:redis-master"
    pid: host
    cap_add:
      - NET_ADMIN
